dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: Ql9jl94IjajkvNbg8oKitjmehrOOhvD009ofn+Z3vS+jYU4voeAmPjVYzuZLTW8ZTsrXc5266VqtHuSSCxe79uZkGJiABMnHSxlnItk5/x++hg1B3SmERCksZVQ2Y7ay4srOExiYcAa7crCLKAfViQ8MVq8OmbFnnDEVW800FpFhobtBwmVA39ZRc9hHAzMQlYRw3q5Jkpxv1NO5QxZEtjjU2XeElEfqczrhrXYisoHiZwh6/v2KIn3+r62trP87ruQDidrAyNRj5Rws2li2gOK8EzY8QE7iSJzPusk76sKrDT/pAg9uSY7z/D6GokNL0l9m2K8YH8xbpzXQTDIp5jaJxrsrJUwmTll6Iq8w6gRJC759qRw5SsYRNgZNpap3c4CoAexCNZUgak7nN6FYk0b/oORrhzgDWi5od5bG+lkZolLJ1N7cQ1Q3Zl9z6ozqjPODg/6gsFe1+gLFWx+J7pbRIrJBFZ670BUCQFUIIDx7c8iPT8I+ohkqd/AiHb2fDQMN8sG2ygb4fXm8HASJri4Xh800nVR4dWYv3fTDl3lQgqc/Dqt9gxnYkTHK5V545LdbgKxT4wcua1c3ypr3A5q3G5cViATvb1G+EIpTazyISBOXS57sZOhTX8qyxXx5StWczpL+qTCfznwT36zjXqoYb7Z8NfdQ1pY/imlHu6A=
  - secure: QJonjIuZSdvRRcqsYaWWT2bAX283XqqINkEuZiEWElQtpuhpt8tmk+isYKQN4zE9ALN8KQUzfuPdO/TcIVehWQvwJoPmkapBpnfon9obqxep5gFcPXsWtCa5ayQG87Obq8AlAWahG8LmIN5EeQwvE+qRI6QWK6d881F9CljDx80rFfN8JZZuUrDikqlkeLwZCVgh/3X+dgYi9ALF+InuBPMlEUTxm7WFh086OgJ1FJJDF0PceX89nu458dELnv5onyyRtAk4b3lBXp9LvXDNqeHeABaYYdyx9Ao8+5TASBtmlrURWnUOBmN03QDQwShE9QxVS1UGDDoLrVZvz9GUqVAuIuxSNCAQPRK19VXjKycNDSrrupU4pgCbma/7gjLQyQ3E/tXiz0YpIwE3UI59EiTYPZ4FfTkgYQ0eiJip2LFkMexaX88ZnqS64PyYUmwTHaO4+2y1R8AIY09BVb8Wj8REFJYqa5jm+5PkRIsoYa04I2of8BCnGUWh7qixmHF99ULLLntjKQC+/EDHJ7UjzxOP+SyyE3ujr1Pe9RVAczYYdxVcYMAdvWfxfnC2PSMDIMJfSPFf0pOov1gRetKou9VVXS45MMkE21vWsj175ZXcR15P12dNE4wPAo+Ji9fuCiZZq6i7v72hAWPB7gY7eyBkG0SkfiXNN5f5k2VUf+s=
  - secure: luUDbVDnKXsJ/C+fkDHtKufhtuSEGlzZMQCITvEJiGmmjZdcgrM9fHRsov9T2Le3Sh2o6NiB9kVI+AWyTptRUGkPepgWMZMTvZLxjzhJhulDaT4heHyY7VKfrLZTvNPPY6gEY/kZ/G/MYc2MDIcvZvgAI1k70y1Oh7LOc8xQgJoAcbncwG3VpKn3KAsluLTuWd8kNpuGm9F5qZvtQbY+aXXri5N5206Zc4x4Ka57VHCW3h3lctjYXbg3XpWvaYI6yHL6IC5ITuPUi7PdUc6hBBSku+A+hMKY2Ag3tmofjtJY9NaoZPwRJiKXGdt3x06WiSoPB9VxHDmJZ3wGGaRZqEsDihMXolpYPubuw413V7DetdpdogNlLfyE2rSwQ7Y7dLrOvNyPoDX5IcRI1fBMxidhEj/DCSo3FrLOLODlE3vP+D6wzYW0O/eMbhxlCwElfMoq7rGaGy6JCVx7eAOKRoUlQBAQ73XRuDz0F0Kwj6QF3L4L7BOUcAdmHb6Sl7CzgKTZE90xY1zasHrIVrMVVqETs5u7Zb2sVHXvaOU7jMqPyw3uijdKHXXvbzKoh2wMefc6cv66iTcxHSJ+9W235ikSsfqMuLuYQn66/fSd6rGr4kveI4uVfGfE6FQMOIMTRuo94LdnznXE4f6wVpd1CdGlH5LtSNtQynLxaHTVdMs=
  - secure: Sa8vEdGhLAu4cfh6J/QihIw6CcRCS46Xl1hyczK4BoAma6XRgfWJ5Znvuzz2hV3lW9Nn6nDgdD4DNKW1DuLegQKO9sC2f/JNPltiMV1lmUrvTrJ6qu8Ph+gvg5PzpTk8NvqCYfRMILUVyPPZgtjkxuaGRd8zJBTs3m6K5ToN/XHouc0IgfXlsn6+mlMObU6N7HutSaVb/hBNmqneHCfAib878j0dZ8/mLohrozCjDBGYSZ234RR20X0nGOFCooi+IZDUCoZ3lFRzPoPIf0wVat40r7V3eDhqzJYwlf2WDahLYR/fV9nz4zLhpvSFqy76YFtvg/ZuYBfxtAjrIxRaozi2sAnJbGWjeeuIwB3jxZ4sgD5pLImyV5HLlfeLYAp8I6UK+HLYM6whMrkvQcacHV+eC0zQiHb0UVY3TuJyqpMODCsY86kr1GpumvDkHSGPlKqYx/UCnVwZx1Q4P0X4cWLKubqB+mYQKjPG7RmxVeXK9DXtFedDYZqKkywyV6y8okvPH9KjLJdhwZgNpfv8AlRWwV+0yP1WFyLuj37LfyrVurfi3MW9dAIUZw7P4zd1Fr3sDIFG62jWjVGOYFFec1+doHE8dL5q64UWQHf7tAJ/+KGRTYHI/s5aPXns429fqmGdKp5qpRP/0WEkawyroGZjx9IvmuvAqwrVPHaMjaU=
install: nvm install 7.9.0
script: bash src/main/scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: cbEFlQbe1vzV2Ej4jZDYG1dV+hyjqJbvWLRcwz34Y1qhMKZ0T93k1icr+6nCEvfya6oDy8z8kkDu666F8GiUux7fHj4OPIxLSK9vn9O5FaBudo1bo1udNkAzYGvCbpN9/rdjyg6ApiEgvgbuOIAsvpfhkjlETRLwoB6sIi2x9Jq/UkLm10/6OpN8eEV5i5BGVylvvOicfbFhlGOrjl3/m49HRbMlb5jBv+GswN7KWp94bum47bGIR2AmnmbQvotNxVEVvVpyJzq8FKPmniZzNdutR/z3jfB0+5t353pZKpRXiAuAzLg/5nhe/7zexQOiYC2S6NmLI/3IzjvDeduUQUl342XqEQdqEcrhaEUaw9PNfkRue7e0AgftQAJpRtdcnRmBLDVTLBzzaDHZx/6zTfwpRJoH5nm5pc0f0Tc/1dDOKcUCU3SsZn60FSxOl//HYbK7uG+eju1CSKVgNsc1bKdvoR56i0ax0+g9gzsgTGmjdmUhoF9nqOsF4oxgJKbL2+/5jh+9sutJVYJjfQG2b+FaVkA3mhptM3YNbBWPZaUYT6ylqumbjTGESi5lWEJ71fXu11vSGrJs4phKEMXrKrBauFlaFHYI8gXODdkTsKyeYTd1voK7biVcWNATXMzq1mDkEhIfgYTjlUqjsMr6hhdsatrZE9bcU3l0tBI2Gss=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(staging|(m|rc)\\.[0-9]+))?$"
after_deploy:
- bash src/main/scripts/gh-publish.bash $TRAVIS_REPO_SLUG
